### ISSUE TITLE
Error after updating to 0.1.12

### ISSUE THREAD

**Issue by sanjeevkpandit** [angular/in-memory-web-api#58]
I got this error after updating to `0.1.12`.
```
Failed to load resource: the server responded with a status of 404 (Not Found)
Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/traceur
	Error: XHR error (404 Not Found) loading http://localhost:3000/traceur
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js:698:29)
	    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:265:35)
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:154:47)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:335:33)
	Error loading http://localhost:3000/traceur
	Unable to load transpiler to transpile http://localhost:3000/node_modules/angular-in-memory-web-api/index.js
	Error loading http://localhost:3000/node_modules/angular-in-memory-web-api/index.js as "angular-in-memory-web-api" from http://localhost:3000/app/app.module.js
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js:698:29)
	    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:265:35)
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:154:47)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:335:33)
	Error loading http://localhost:3000/traceur
	Unable to load transpiler to transpile http://localhost:3000/node_modules/angular-in-memory-web-api/index.js
	Error loading http://localhost:3000/node_modules/angular-in-memory-web-api/index.js as "angular-in-memory-web-api" from http://localhost:3000/app/app.module.js
```

We also tried it in [angular.io quickstart](https://angular.io/docs/ts/latest/tutorial/) but got the same error.

The application works with the older versions(`0.1.9` and `0.1.10`) without any errors.

Please let us know if you need something else.

**Comment by orzeh** [comment]
Try to upgrade to 0.1.13 and fix your configuration according to the [RELEASE_NOTES](https://github.com/angular/in-memory-web-api/blob/master/CHANGELOG.md#0113-2016-10-20)

**Comment by sanjeevkpandit** [comment]
@orzeh I tried using 0.1.13 and updated the configuration, but the same error occurs.

**Comment by orzeh** [comment]
@sanjeevkpandit if you follow [chapter 7 HTTP](https://angular.io/docs/ts/latest/tutorial/toh-pt6.html#simulating-the-web-api) form the angular.io Tour of Heroes tutorial change your `app.module.ts` from:

````js
// Imports for loading & configuring the in-memory web api
import { InMemoryWebApiModule } from 'angular-in-memory-web-api/in-memory-web-api.module';
````
to:
````js
// Imports for loading & configuring the in-memory web api
import { InMemoryWebApiModule } from 'angular-in-memory-web-api';
````
as mentioned in the [README](https://github.com/angular/in-memory-web-api#basic-usage).

**Comment by coklin3107** [comment]
ohh I have the same problem..

**Comment by sanjeevkpandit** [comment]
@orzeh I did the same thing as mentioned in [RELEASED_NOTES](https://github.com/angular/in-memory-web-api/blob/master/CHANGELOG.md#0113-2016-10-20) and [README](https://github.com/angular/in-memory-web-api#basic-usage) but, no luck.

**Comment by coklin3107** [comment]
@sanjeevkpandit  please sent my your systems.config.js or make sure you did this after update

 change the mapping to:
```
'angular-in-memory-web-api': 'npm:angular-in-memory-web-api/bundles/in-memory-web-api.umd.js'

then delete from packages:

'angular-in-memory-web-api': {

    main: './index.js',

    defaultExtension: 'js'

  }
```

**Comment by sanjeevkpandit** [comment]
@coklin3107 I forgot to remove from the packages. It's working now. Thanks!
